### ISSUE TITLE
Question: where do I find 'decibels'?

### ISSUE THREAD

**Issue by rahuldeo2047** [scijs/fourier-transform#7]
$ node --version
v6.12.3
$ node
`>  var db = require('decibels');
`
```
module.js:471
    throw err;
    ^

Error: Cannot find module 'decibels'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/test/code.js:96:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

```
`> var ft = require('fourier-transform');`
undefined
`> ft`
[Function: rfft]
`> `

**Comment by dy** [comment]
https://github.com/audiojs/decibels

**Comment by rahuldeo2047** [comment]
:P sorry. I missed that.
